#!/usr/bin/env bash

chainsplit() {
  file="$1"
  awk '
    split_after == 1 {n++;split_after=0}
    /-----END CERTIFICATE-----/ {split_after=1}
    {print > "cert" n ".pem"}' < $file
}

TEMPLATErenew() {
  cp /etc/letsencrypt/live/TEMPLATE/privkey.pem /srv/persist/TEMPLATE-key/privkey.pem
  chainsplit /srv/persist/TEMPLATE-cert/fullchain.pem
  cat cert.pem cert1.pem > /srv/persist/TEMPLATE-cert/cert.pem
}

TEMPLATErenew

ash /root/loader.sh
